// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_base_bean.proto
package com.fcsbbc.common.bean;

public final class UserBaseBean {
  private UserBaseBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserGeneralOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserGeneral)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_id = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string user_name = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string user_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string user_password = 3;</code>
     */
    java.lang.String getUserPassword();
    /**
     * <code>string user_password = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserPasswordBytes();

    /**
     * <code>string user_telephone = 4;</code>
     */
    java.lang.String getUserTelephone();
    /**
     * <code>string user_telephone = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserTelephoneBytes();

    /**
     * <code>int32 user_role = 5;</code>
     */
    int getUserRole();

    /**
     * <code>string user_ca_path = 6;</code>
     */
    java.lang.String getUserCaPath();
    /**
     * <code>string user_ca_path = 6;</code>
     */
    com.google.protobuf.ByteString
        getUserCaPathBytes();

    /**
     * <code>int32 is_active = 7;</code>
     */
    int getIsActive();

    /**
     * <code>string user_system_id = 8;</code>
     */
    java.lang.String getUserSystemId();
    /**
     * <code>string user_system_id = 8;</code>
     */
    com.google.protobuf.ByteString
        getUserSystemIdBytes();

    /**
     * <code>string generate_time = 9;</code>
     */
    java.lang.String getGenerateTime();
    /**
     * <code>string generate_time = 9;</code>
     */
    com.google.protobuf.ByteString
        getGenerateTimeBytes();
  }
  /**
   * Protobuf type {@code UserGeneral}
   */
  public  static final class UserGeneral extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserGeneral)
      UserGeneralOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserGeneral.newBuilder() to construct.
    private UserGeneral(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserGeneral() {
      userId_ = "";
      userName_ = "";
      userPassword_ = "";
      userTelephone_ = "";
      userRole_ = 0;
      userCaPath_ = "";
      isActive_ = 0;
      userSystemId_ = "";
      generateTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserGeneral(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userPassword_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userTelephone_ = s;
              break;
            }
            case 40: {

              userRole_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              userCaPath_ = s;
              break;
            }
            case 56: {

              isActive_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              userSystemId_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              generateTime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserBaseBean.internal_static_UserGeneral_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserBaseBean.internal_static_UserGeneral_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserBaseBean.UserGeneral.class, UserBaseBean.UserGeneral.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string user_id = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>string user_name = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string user_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object userPassword_;
    /**
     * <code>string user_password = 3;</code>
     */
    public java.lang.String getUserPassword() {
      java.lang.Object ref = userPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPassword_ = s;
        return s;
      }
    }
    /**
     * <code>string user_password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserPasswordBytes() {
      java.lang.Object ref = userPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_TELEPHONE_FIELD_NUMBER = 4;
    private volatile java.lang.Object userTelephone_;
    /**
     * <code>string user_telephone = 4;</code>
     */
    public java.lang.String getUserTelephone() {
      java.lang.Object ref = userTelephone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userTelephone_ = s;
        return s;
      }
    }
    /**
     * <code>string user_telephone = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserTelephoneBytes() {
      java.lang.Object ref = userTelephone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userTelephone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ROLE_FIELD_NUMBER = 5;
    private int userRole_;
    /**
     * <code>int32 user_role = 5;</code>
     */
    public int getUserRole() {
      return userRole_;
    }

    public static final int USER_CA_PATH_FIELD_NUMBER = 6;
    private volatile java.lang.Object userCaPath_;
    /**
     * <code>string user_ca_path = 6;</code>
     */
    public java.lang.String getUserCaPath() {
      java.lang.Object ref = userCaPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userCaPath_ = s;
        return s;
      }
    }
    /**
     * <code>string user_ca_path = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserCaPathBytes() {
      java.lang.Object ref = userCaPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userCaPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_ACTIVE_FIELD_NUMBER = 7;
    private int isActive_;
    /**
     * <code>int32 is_active = 7;</code>
     */
    public int getIsActive() {
      return isActive_;
    }

    public static final int USER_SYSTEM_ID_FIELD_NUMBER = 8;
    private volatile java.lang.Object userSystemId_;
    /**
     * <code>string user_system_id = 8;</code>
     */
    public java.lang.String getUserSystemId() {
      java.lang.Object ref = userSystemId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userSystemId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_system_id = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUserSystemIdBytes() {
      java.lang.Object ref = userSystemId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userSystemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENERATE_TIME_FIELD_NUMBER = 9;
    private volatile java.lang.Object generateTime_;
    /**
     * <code>string generate_time = 9;</code>
     */
    public java.lang.String getGenerateTime() {
      java.lang.Object ref = generateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        generateTime_ = s;
        return s;
      }
    }
    /**
     * <code>string generate_time = 9;</code>
     */
    public com.google.protobuf.ByteString
        getGenerateTimeBytes() {
      java.lang.Object ref = generateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        generateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (!getUserPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPassword_);
      }
      if (!getUserTelephoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userTelephone_);
      }
      if (userRole_ != 0) {
        output.writeInt32(5, userRole_);
      }
      if (!getUserCaPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userCaPath_);
      }
      if (isActive_ != 0) {
        output.writeInt32(7, isActive_);
      }
      if (!getUserSystemIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userSystemId_);
      }
      if (!getGenerateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, generateTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (!getUserPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPassword_);
      }
      if (!getUserTelephoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userTelephone_);
      }
      if (userRole_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, userRole_);
      }
      if (!getUserCaPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userCaPath_);
      }
      if (isActive_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, isActive_);
      }
      if (!getUserSystemIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, userSystemId_);
      }
      if (!getGenerateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, generateTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserBaseBean.UserGeneral)) {
        return super.equals(obj);
      }
      UserBaseBean.UserGeneral other = (UserBaseBean.UserGeneral) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getUserPassword()
          .equals(other.getUserPassword());
      result = result && getUserTelephone()
          .equals(other.getUserTelephone());
      result = result && (getUserRole()
          == other.getUserRole());
      result = result && getUserCaPath()
          .equals(other.getUserCaPath());
      result = result && (getIsActive()
          == other.getIsActive());
      result = result && getUserSystemId()
          .equals(other.getUserSystemId());
      result = result && getGenerateTime()
          .equals(other.getGenerateTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USER_PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getUserPassword().hashCode();
      hash = (37 * hash) + USER_TELEPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getUserTelephone().hashCode();
      hash = (37 * hash) + USER_ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getUserRole();
      hash = (37 * hash) + USER_CA_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getUserCaPath().hashCode();
      hash = (37 * hash) + IS_ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + getIsActive();
      hash = (37 * hash) + USER_SYSTEM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserSystemId().hashCode();
      hash = (37 * hash) + GENERATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getGenerateTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserBaseBean.UserGeneral parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserBaseBean.UserGeneral parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserBaseBean.UserGeneral parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserBaseBean.UserGeneral parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserBaseBean.UserGeneral parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserBaseBean.UserGeneral parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserBaseBean.UserGeneral parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserBaseBean.UserGeneral parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserBaseBean.UserGeneral parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserBaseBean.UserGeneral parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserBaseBean.UserGeneral parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserBaseBean.UserGeneral parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserBaseBean.UserGeneral prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserGeneral}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserGeneral)
        UserBaseBean.UserGeneralOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserBaseBean.internal_static_UserGeneral_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserBaseBean.internal_static_UserGeneral_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserBaseBean.UserGeneral.class, UserBaseBean.UserGeneral.Builder.class);
      }

      // Construct using UserBaseBean.UserGeneral.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        userName_ = "";

        userPassword_ = "";

        userTelephone_ = "";

        userRole_ = 0;

        userCaPath_ = "";

        isActive_ = 0;

        userSystemId_ = "";

        generateTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserBaseBean.internal_static_UserGeneral_descriptor;
      }

      public UserBaseBean.UserGeneral getDefaultInstanceForType() {
        return UserBaseBean.UserGeneral.getDefaultInstance();
      }

      public UserBaseBean.UserGeneral build() {
        UserBaseBean.UserGeneral result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UserBaseBean.UserGeneral buildPartial() {
        UserBaseBean.UserGeneral result = new UserBaseBean.UserGeneral(this);
        result.userId_ = userId_;
        result.userName_ = userName_;
        result.userPassword_ = userPassword_;
        result.userTelephone_ = userTelephone_;
        result.userRole_ = userRole_;
        result.userCaPath_ = userCaPath_;
        result.isActive_ = isActive_;
        result.userSystemId_ = userSystemId_;
        result.generateTime_ = generateTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserBaseBean.UserGeneral) {
          return mergeFrom((UserBaseBean.UserGeneral)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserBaseBean.UserGeneral other) {
        if (other == UserBaseBean.UserGeneral.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getUserPassword().isEmpty()) {
          userPassword_ = other.userPassword_;
          onChanged();
        }
        if (!other.getUserTelephone().isEmpty()) {
          userTelephone_ = other.userTelephone_;
          onChanged();
        }
        if (other.getUserRole() != 0) {
          setUserRole(other.getUserRole());
        }
        if (!other.getUserCaPath().isEmpty()) {
          userCaPath_ = other.userCaPath_;
          onChanged();
        }
        if (other.getIsActive() != 0) {
          setIsActive(other.getIsActive());
        }
        if (!other.getUserSystemId().isEmpty()) {
          userSystemId_ = other.userSystemId_;
          onChanged();
        }
        if (!other.getGenerateTime().isEmpty()) {
          generateTime_ = other.generateTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserBaseBean.UserGeneral parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserBaseBean.UserGeneral) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string user_name = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_name = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 2;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPassword_ = "";
      /**
       * <code>string user_password = 3;</code>
       */
      public java.lang.String getUserPassword() {
        java.lang.Object ref = userPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserPasswordBytes() {
        java.lang.Object ref = userPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_password = 3;</code>
       */
      public Builder setUserPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_password = 3;</code>
       */
      public Builder clearUserPassword() {
        
        userPassword_ = getDefaultInstance().getUserPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string user_password = 3;</code>
       */
      public Builder setUserPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPassword_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userTelephone_ = "";
      /**
       * <code>string user_telephone = 4;</code>
       */
      public java.lang.String getUserTelephone() {
        java.lang.Object ref = userTelephone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userTelephone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_telephone = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserTelephoneBytes() {
        java.lang.Object ref = userTelephone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userTelephone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_telephone = 4;</code>
       */
      public Builder setUserTelephone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userTelephone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_telephone = 4;</code>
       */
      public Builder clearUserTelephone() {
        
        userTelephone_ = getDefaultInstance().getUserTelephone();
        onChanged();
        return this;
      }
      /**
       * <code>string user_telephone = 4;</code>
       */
      public Builder setUserTelephoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userTelephone_ = value;
        onChanged();
        return this;
      }

      private int userRole_ ;
      /**
       * <code>int32 user_role = 5;</code>
       */
      public int getUserRole() {
        return userRole_;
      }
      /**
       * <code>int32 user_role = 5;</code>
       */
      public Builder setUserRole(int value) {
        
        userRole_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_role = 5;</code>
       */
      public Builder clearUserRole() {
        
        userRole_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userCaPath_ = "";
      /**
       * <code>string user_ca_path = 6;</code>
       */
      public java.lang.String getUserCaPath() {
        java.lang.Object ref = userCaPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userCaPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_ca_path = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUserCaPathBytes() {
        java.lang.Object ref = userCaPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userCaPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_ca_path = 6;</code>
       */
      public Builder setUserCaPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userCaPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_ca_path = 6;</code>
       */
      public Builder clearUserCaPath() {
        
        userCaPath_ = getDefaultInstance().getUserCaPath();
        onChanged();
        return this;
      }
      /**
       * <code>string user_ca_path = 6;</code>
       */
      public Builder setUserCaPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userCaPath_ = value;
        onChanged();
        return this;
      }

      private int isActive_ ;
      /**
       * <code>int32 is_active = 7;</code>
       */
      public int getIsActive() {
        return isActive_;
      }
      /**
       * <code>int32 is_active = 7;</code>
       */
      public Builder setIsActive(int value) {
        
        isActive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 is_active = 7;</code>
       */
      public Builder clearIsActive() {
        
        isActive_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userSystemId_ = "";
      /**
       * <code>string user_system_id = 8;</code>
       */
      public java.lang.String getUserSystemId() {
        java.lang.Object ref = userSystemId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userSystemId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_system_id = 8;</code>
       */
      public com.google.protobuf.ByteString
          getUserSystemIdBytes() {
        java.lang.Object ref = userSystemId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userSystemId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_system_id = 8;</code>
       */
      public Builder setUserSystemId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userSystemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_system_id = 8;</code>
       */
      public Builder clearUserSystemId() {
        
        userSystemId_ = getDefaultInstance().getUserSystemId();
        onChanged();
        return this;
      }
      /**
       * <code>string user_system_id = 8;</code>
       */
      public Builder setUserSystemIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userSystemId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object generateTime_ = "";
      /**
       * <code>string generate_time = 9;</code>
       */
      public java.lang.String getGenerateTime() {
        java.lang.Object ref = generateTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          generateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string generate_time = 9;</code>
       */
      public com.google.protobuf.ByteString
          getGenerateTimeBytes() {
        java.lang.Object ref = generateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          generateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string generate_time = 9;</code>
       */
      public Builder setGenerateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        generateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string generate_time = 9;</code>
       */
      public Builder clearGenerateTime() {
        
        generateTime_ = getDefaultInstance().getGenerateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string generate_time = 9;</code>
       */
      public Builder setGenerateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        generateTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserGeneral)
    }

    // @@protoc_insertion_point(class_scope:UserGeneral)
    private static final UserBaseBean.UserGeneral DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserBaseBean.UserGeneral();
    }

    public static UserBaseBean.UserGeneral getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserGeneral>
        PARSER = new com.google.protobuf.AbstractParser<UserGeneral>() {
      public UserGeneral parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserGeneral(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserGeneral> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserGeneral> getParserForType() {
      return PARSER;
    }

    public UserBaseBean.UserGeneral getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserGeneral_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserGeneral_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024user_base_bean.proto\"\313\001\n\013UserGeneral\022\017" +
      "\n\007user_id\030\001 \001(\t\022\021\n\tuser_name\030\002 \001(\t\022\025\n\rus" +
      "er_password\030\003 \001(\t\022\026\n\016user_telephone\030\004 \001(" +
      "\t\022\021\n\tuser_role\030\005 \001(\005\022\024\n\014user_ca_path\030\006 \001" +
      "(\t\022\021\n\tis_active\030\007 \001(\005\022\026\n\016user_system_id\030" +
      "\010 \001(\t\022\025\n\rgenerate_time\030\t \001(\tB\016B\014UserBase" +
      "Beanb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserGeneral_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserGeneral_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserGeneral_descriptor,
        new java.lang.String[] { "UserId", "UserName", "UserPassword", "UserTelephone", "UserRole", "UserCaPath", "IsActive", "UserSystemId", "GenerateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
